### ISSUE TITLE
PCB Problem

### ISSUE THREAD

**Issue by foorschtbar** [LeoDJ/Caution-Hot-PCB-Sign#1]
JLCPCB had problems to detect the outlines. Then I tried to open the KiCAD files to plot the Gerber files, but unfortunately KiCAD says your version is too new. I use the official stable 5.10.1 Version and cant open the project :(

**Comment by LeoDJ** [comment]
Yes, the gerber preview on JLCPCB had problems with the outline too when I ordered it. But it wasn't a real problem and was produced without an issue and the correct outline.

The project was built with the current KiCad nightly, so it sadly can't be opened with KiCad 5.

**Comment by foorschtbar** [comment]
Okay, thank u! Also for the PCB. Can't wait to put it together :)
